### PR TITLE
Updates to enable WMLA training in MSK env

### PR DESCRIPTION
**Pull request by rich-nieto-ibm**
Simple changes to enable running training on WML-A. Tested by submitting 2- and 4-GPU trainings to WML-A from WS.

### CODE REVIEW

**Comment by wendywwang** [comment]
@rich-nieto-ibm num_threads has to be 0 in wmla? with the old code we don't have this limitation

**Comment by rich-nieto-ibm** [comment]
> @rich-nieto-ibm num_threads has to be 0 in wmla? with the old code we don't have this limitation

You're right @wendywwang, I was being explicit to match your benchmarks--I suppose the commit message shouldn't have been bundled :)

**Comment by wendywangwwt** [comment]
@rich-nieto-ibm then maybe you can take out the changes for `train_command.py` and submit a commit only for the notebook?

**Comment by rich-nieto-ibm** [comment]
@wendywwang done!

**Pull request merged**
