### PR TITLE
fix for inference

### PR DESCRIPTION
**Pull request by wendywwang**

### CODE REVIEW

**Review by drewmibm — APPROVED** [review]
Nothing concerning.  Was Image.fromarray() causing issues for inference?

**Comment by wendywwang** [comment]
@drewmibm it's `tensor2im` - to fix gpu id issues I moved this function from init py to util py, but `image.fromarray()` in inference needs to call a function `tensor_to_pil()` in init.py which expects the already moved `tensor2im`; so I had to find a way to make both happy :/

**Comment by wendywwang** [comment]
eh I guess tensor2im accidentally slipped back into the init py.. I will run a test to verify that once #5 is approved

**Review by rich-nieto-ibm — APPROVED** [review]
Tested in WS

**Pull request merged**
